################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Los_Angeles
  unit_system: imperial
  customize: !include_dir_merge_named customize

frontend:
history:
logbook:
sun:
updater:
emulated_hue:


################################################
## Testing Area
################################################

# TODO: Move alexa intents to separate directory
alexa:
  intents:
    JordanBoyfriend:
      action:
        service: notify.telegram_home_assistant
        data:
          message: Someone asked who is Jordan's boyfriend. 
      speech:
        type: plaintext
        text: >
            Hmm...currently, it is Nathan Erlich.
      card:
        type: simple
        title: Jordan's Boyfriend
        content: Skill used to keep track of who is Jordan's current boyfriend
    LocateIntent:
      action:
        service: notify.telegram_home_assistant
        data_template:
          message: Someone asked where is {{ User }} 
      speech:
        type: plaintext
        text: >
          {% if User.lower() in states.device_tracker|map(attribute='name')|map('lower') %}
              {% if User.lower() == "alex" %}
                  {% if states.device_tracker.alexsiphone6plus.state.lower() == "work" %}
                      Alex is at work.
                  {% elif states.device_tracker.alexsiphone6plus.state.lower() == "not_home" %}
                      Alex is {{states.sensor.alex_to_home.state}} minutes from home.
                  {% else %}
                      Alex is at {{states.device_tracker.alexsiphone6plus.state.lower()}}
                  {% endif %}
              {% elif User.lower() == "amy" %}     
                  {% if states.device_tracker.amysiphone6.state.lower() == "not_home" %}
                      Amy is {{states.sensor.amy_to_home.state }} minutes from home.
                  {% else %}
                      Amy is at {{states.device_tracker.amysiphone6.state.lower()}}
                  {% endif %}
              {% else %}
                   I am currently not tracking {{User}}'s location.
              {% endif %}
          {% else %}
              I have no idea who {{User}} is. 
          {% endif %}
      card:
        type: simple
        title: Locate Family
        content: Skill used to help locate family members

################################################
## Components (Non-Includes)
################################################

http:
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key


ifttt:
  key: !secret ifttt_key

recorder:
  purge_days: 7

mqtt:
  broker: 10.0.1.125
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

################################################
## Component Includes (Single File)
################################################

logger: !include logger.yaml
zwave: !include zwave.yaml

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list device_tracker
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensors
zone: !include_dir_merge_list zone

################################################
## Component Includes (Merge Named)
################################################

group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
