################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Los_Angeles
  unit_system: imperial
  customize: !include_dir_merge_named customize

frontend:
logbook:
sun:
updater:
  include_used_components: true
  reporting: False

emulated_hue:
  type: alexa
  expose_by_default: false

################################################
## Testing Area
################################################
history:
  include:
    entities:
      - sensor.downstairs_temperature
      - sensor.family_room_temperature
      - sensor.bedroom_temperature
      - sensor.jordans_room_temperature
      - sensor.olivias_room_temperature
      - sensor.playroom_temperature
      - device_tracker.alexiphone
      - device_tracker.amyiphone
      - device_tracker.jordaniphone
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.cpu_temperature
      - binary_sensor.downstairs_occupancy
      - binary_sensor.family_room_occupancy
      - binary_sensor.jordans_room_occupancy
      - binary_sensor.olivias_room_occupancy
      - binary_sensor.playroom_occupancy
      - binary_sensor.bedroom_occupancy


alexa:
  intents: !include_dir_named alexa

################################################
## Components (Non-Includes)
################################################

http:
  api_password: !secret http_api_password
  server_port: !secret http_server_port
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key 
    allowed_chat_ids:
      - !secret telegram_home_chat_id
      - !secret telegram_home_assistant_id

ifttt:
  key: !secret ifttt_key

ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: false

recorder:
  purge_days: 7

mqtt:
  broker: 10.0.1.125
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

################################################
## Component Includes (Single File)
################################################

logger: !include logger.yaml
zwave:
  usb_path: /dev/zwave
  new_entity_ids: true

camera: !include camera/cameras.yaml

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list device_tracker
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
sensor: !include_dir_merge_list sensors
zone: !include_dir_merge_list zone

################################################
## Component Includes (Merge Named)
################################################

group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
