################################################################
## Automation / Alex Work
################################################################
- alias: "Alex Leaves Work"
  trigger:
    - platform: zone
      entity_id: device_tracker.alexsiphone6plus
      zone: zone.work
      event: leave
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.leaving_work
        state: 'on'
      - condition: time
        after: '16:00:00'
        before: '21:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    service: notify.telegram_home_chat
    data:
      message: Alex has left work.

- alias: Increase icloud interval after 4pm
  trigger:
    - platform: time
      after: '16:00:00'
  condition:
    - condition: state
      entity_id: device_tracker.alexsiphone6plus
      state: 'Work'
  action:
    - service: device_tracker.icloud_set_interval
      data:
        account_name: alex
        device_name: alexsiphone6plus
        interval: 1
