###################################
##  ZWave Healing Section
###################################

- alias: Heal ZWave Nightly
  trigger:
    platform: time
    at: '3:30:00'
  action:
    service: zwave.heal_network    
