################################################################
## Media Player
################################################################

- platform: plex
  name: Plex
- platform: roku
  host: 10.0.1.49
  name: Family Roku

