################################################################
## Media Player / Fire TV
################################################################

################################################
## Plex
################################################

- platform: plex
  name: Plex
